### ISSUE TITLE
No Visual mode selection color

### ISSUE THREAD

**Issue by diegombeltran** [crusoexia/vim-monokai#10]
Using XFCE4-Terminal, with a Monokai color theme (256 color). I get transparent selection color when using Visual mode. Don't know if it was intended. I've fixed it by setting this in line 110:

`call s:h("Visual",        {                     "bg": s:lightgrey,    "format": "reverse" })`

**Comment by crusoexia** [comment]
I'm using iterm2 and haven't experience this issue, could you please fire a pr against dev branch? I will check it later
