### ISSUE TITLE
Function expression names aren't highlighted

### ISSUE THREAD

**Issue by cjnucette** [crusoexia/vim-monokai#12]
Hi, i'm having the following issue:
This is how function expressions look in vim

![screenshot from 2016-09-07 18-37-34](https://cloud.githubusercontent.com/assets/2278326/18331081/5e332698-752a-11e6-8399-b5a1eec65bbb.png)

And this is how they look in sublime

![screenshot from 2016-09-07 18-38-09](https://cloud.githubusercontent.com/assets/2278326/18331117/890d10e0-752a-11e6-88bb-865abe9f8dbc.png)

This is the code in text

`/\* eslint-disable no-unused-vars */
const mapWith = (fn) =>
  (list) => list.map(fn);

const reverse = ([first, ...rest], delayed=[]) =>
  first === undefined
    ? delayed
    : reverse(rest, [first, ...delayed]);

const map = ([first, ...rest], fn, delayed=[]) =>
  first === undefined
    ? reverse(delayed)
    : map(rest, fn, [fn(first), ...delayed]);

// This is a comment
const flip = function(fn) {
  return (first) => (second) => fn(second, first);
};
`
And finally i have the following in my .vimrc:

Plug 'https://github.com/mattn/emmet-vim.git'
Plug 'https://github.com/tpope/vim-surround.git'
Plug 'https://github.com/tpope/vim-commentary.git'
Plug 'https://github.com/tpope/vim-repeat.git'
Plug 'raimondi/delimitmate'
Plug 'https://github.com/Valloric/MatchTagAlways.git'
Plug 'https://github.com/terryma/vim-multiple-cursors.git'
Plug 'pangloss/vim-javascript'
Plug 'crusoexia/vim-javascript-lib'
Plug 'Shougo/vimproc.vim', {'do': 'make'}
Plug 'Quramy/tsuquyomi'
Plug 'leafgarland/typescript-vim'
Plug 'mxw/vim-jsx'
Plug 'othree/html5.vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'elzr/vim-json'
Plug 'maksimr/vim-jsbeautify', {'do': 'git submodule update --init --recursive'}
Plug 'scrooloose/syntastic'
Plug 'https://github.com/tpope/vim-fugitive.git'
Plug 'airblade/vim-gitgutter'
Plug 'ternjs/tern_for_vim', {'do': 'npm install'}
Plug 'valloric/YouCompleteMe', {'do': './install.py --tern-completer'}
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'edkolev/promptline.vim'
Plug 'edkolev/tmuxline.vim'
Plug 'ap/vim-css-color'
Plug 'editorconfig/editorconfig-vim'
Plug 'http://github.com/crusoexia/vim-monokai.git'
Plug 'https://github.com/joshdick/onedark.vim.git'
Plug 'jacoborus/tender'
Plug 'lifepillar/vim-solarized8'
Plug 'mhartington/oceanic-next'

**Comment by crusoexia** [comment]
I will check whether [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) support it.

**Comment by crusoexia** [comment]
@cjnucette there is a syntax match in [vim-javascript](https://github.com/pangloss/vim-javascript) called jsVariableDef, however, it will not only match the function variable Definition, but also other type of variables, which means `var1` and `var2` will have same hignlight.
     const var1 = 100
     const var2 = () => ()
This is not the expect result.

I suggest you to go to [vim-javascript](https://github.com/pangloss/vim-javascript) to provide a separate syntax match for function and other type of variables. After that, we can solve this problem
