### ISSUE TITLE
Transparency Control

### ISSUE THREAD

**Issue by kenmarshall** [crusoexia/vim-monokai#14]
How can I adjust the transparency?

The transparency settings only change for the terminal but not vim when this theme is used.

I tried this online answer:  `hi Normal ctermbg=NONE`
It worked, but the line numbers still weren't transparent.

**Comment by kenmarshall** [comment]
`hi LineNr ctermbg=NONE` seem to did the trick, but these hacks seem to just remove these from vim as oppose to adjusting transparency.

It would be nice to do something like
`let g:monokai_transparency=0.5`

**Comment by crusoexia** [comment]
good suggestion, will add in next update.

**Comment by crusoexia** [comment]
@kenmarshall, vim it self cannot config the transparency level. I suggest you to use [neovim](https://neovim.io/), it support inherit the transparent setting from the terminal without any other additional settings.
