### ISSUE TITLE
Does monokai support truecolor mode even in the terminal?

### ISSUE THREAD

**Issue by chrisbra** [crusoexia/vim-monokai#15]
Hi,
I am just wondering, does this colorscheme support truecolor mode in the terminal (`:set termguicolors` in Vim)?

Thanks.

**Comment by crusoexia** [comment]
You need a terminal which support truecolor like *iterm2*.

**Comment by chrisbra** [comment]
That means, monokai supports termguicolors? (I am not asking about terminals which support this functionality, that was beside the question)

**Comment by crusoexia** [comment]
Yes, it supports.
