### ISSUE TITLE
distribute with vim?

### ISSUE THREAD

**Issue by chrisbra** [crusoexia/vim-monokai#16]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by crusoexia** [comment]
Sure, it will be my honor.

**Comment by chrisbra** [comment]
Great.
Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. If you would like to do it mention that this is for issue 1665 to fix it. Thanks!

**Comment by crusoexia** [comment]
That's fine, I will send the file
