### ISSUE TITLE
MatchParen active brace should get a brighter color than the matching brace

### ISSUE THREAD

**Issue by cyberang3l** [crusoexia/vim-monokai#17]
The cursor is typically a bright white color. When the cursor suddenly goes over a parenthesis it becomes black and the matching parenthesis becomes purple and is much brighter than the parenthesis where the cursor is over.

That behavior always confuses me since the bright white cursor almost disappears and suddenly appears as bright (in purple) somewhere else.

I have experimented a little bit with different fg/bg colors for the `MatchParen` group, and having a white fg color and grey bg or purple fg and black bg makes it much easier to follow the active cursor. 

In general, as long as the active cursor is brighter than the matching parenthesis cursor it is probably easier to follow.

The following worked best for me, since when the bg (i.e. the matching parenthesis) becomes black, it might be hard to spot (especially when it is not at the same line and you have multiple parentheses around):

`call s:h("MatchParen",    { "fg": s:white,      "bg": s:grey })`

**Comment by crusoexia** [comment]
Thanks to rise the issue up, I will check on that.

**Comment by crusoexia** [comment]
Hi @cyberang3l,

I haven't experienced the issue you mentioned, please confirm whether your case is the same as below screenshot. If not, please take a screenshot.

<img width="245" alt="screen shot 2018-05-11 at 9 45 04 pm" src="https://user-images.githubusercontent.com/5928754/39927394-a6efeea4-5564-11e8-8280-9470162e5fa9.png">

**Comment by crusoexia** [comment]
Do you mean in the editing mode?

<img width="246" alt="screen shot 2018-05-11 at 10 06 16 pm" src="https://user-images.githubusercontent.com/5928754/39928341-a790cf42-5567-11e8-90d6-2659e406c5fd.png">

**Comment by cyberang3l** [comment]
Take a look at the attached animated GIF of what I see:
![black-purple](https://user-images.githubusercontent.com/5658474/39928244-23904222-5535-11e8-9e2f-26044622c000.gif)

As you notice the cursor in the active position almost disappears.

If I apply the following patch things look much better:
```diff
diff --git a/colors/monokai.vim b/colors/monokai.vim
index 7f425d9..a79acb6 100644
--- a/colors/monokai.vim
+++ b/colors/monokai.vim
@@ -109,7 +109,7 @@ call s:h("StatusLineNC",  { "fg": s:darkgrey,   "bg": s:warmgrey,     "format":
 call s:h("TabLine",       { "fg": s:white,      "bg": s:darkblack,    "format": "reverse" })
 call s:h("Visual",        {                     "bg": s:lightgrey })
 call s:h("Search",        { "fg": s:black,      "bg": s:yellow })
-call s:h("MatchParen",    { "fg": s:black,      "bg": s:purple })
+call s:h("MatchParen",    { "fg": s:white,      "bg": s:grey })
 call s:h("Question",      { "fg": s:yellow })
 call s:h("ModeMsg",       { "fg": s:yellow })
 call s:h("MoreMsg",       { "fg": s:yellow })
```

![white-grey](https://user-images.githubusercontent.com/5658474/39928347-62329296-5535-11e8-8684-a947f91b2e0b.gif)

**Comment by crusoexia** [comment]
It looks terrible, but behaves different from mine. I'm using neovim on iterm, os x. Which vim client are you using, GUI or terminal?

**Comment by crusoexia** [comment]
Reproduced on my local machine, mac os x native terminal, with below settings

```vimscript
  set t_Co=256
  "let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
  "set termguicolors
```

With the `termguicolors` it works well. Start to fixing this issue. Thank you, @cyberang3l.

**Comment by crusoexia** [comment]
The cursor is defined by terminal, after change the terminal setting the cursor become white. I think it is a different case from yours. Still need your vim client, terminal infos, also your `.vimrc` might be helpful.

**Comment by crusoexia** [comment]
Will below changes helps?
```diff
diff --git a/colors/monokai.vim b/colors/monokai.vim
index 7f425d9..a80fd5c 100644
--- a/colors/monokai.vim
+++ b/colors/monokai.vim
@@ -101,6 +101,7 @@ let s:changebg    = { "gui": "#5f5f87", "cterm": "60" }
 " editor
 call s:h("Normal",        { "fg": s:white,      "bg": s:black })
 call s:h("ColorColumn",   {                     "bg": s:lightblack })
+call s:h("Cursor",        { "fg": s:black,      "bg": s:white })
 call s:h("CursorColumn",  {                     "bg": s:lightblack2 })
 call s:h("CursorLine",    {                     "bg": s:lightblack2 })
 call s:h("NonText",       { "fg": s:lightgrey })
```

**Comment by cyberang3l** [comment]
I tried the suggested change and it doesn't work :(

You can find my vimrc here: https://gist.github.com/cyberang3l/ba53f569d33d66c246add0f5e7d5d0a4

I use KDE neon which is based on Ubuntu 16.04 and you can see my vim version and `$TERM` below: 
```
$ apt-cache policy vim
vim:
  Installed: 2:7.4.1689-3ubuntu1.2
  Candidate: 2:7.4.1689-3ubuntu1.2
  Version table:
 *** 2:7.4.1689-3ubuntu1.2 500
        500 http://no.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2:7.4.1689-3ubuntu1 500
        500 http://no.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

```
$ echo $TERM 
xterm-256color
```

If there is anything else you need let me know!

**Comment by crusoexia** [comment]
I will setup a VM to try to reproduce, it may take some times.

**Comment by cyberang3l** [comment]
Awesome :)
Works exactly as in the screenshot!
Thanks!
