### ISSUE TITLE
Highlight for spelling errors is disable? 

### ISSUE THREAD

**Issue by pqks** [crusoexia/vim-monokai#23]
Hi,
I use this theme on terminal, for consistence I've added on my .vimrc: `set termguicolors`, but when i did that, vim loses the highlight of spell check. If I want use the spell highlight I must disable `termguicolors` and when it happens the background color is inconsistent.

![3](https://user-images.githubusercontent.com/39012860/57639708-1fb42080-7576-11e9-87f9-f194b20f59e9.png)

**Specs**: 
OS: Debian 9
Vim: 8.0.707  
Terminal: xfce-terminal 0.8.3 

**PD:** With themes [Dracula](https://github.com/dracula/vim) and [Pencil](https://github.com/reedes/vim-colors-pencil) spell check works, maybe this info help.

**Comment by crusoexia** [comment]
What spell check plugin you are using?

**Comment by pqks** [comment]
Vim's default:  `:set spell`

**Comment by crusoexia** [comment]
@pqks the spell check highlight added. Hope you like it.

<img width="274" alt="Screen Shot 2019-05-22 at 2 40 26 PM" src="https://user-images.githubusercontent.com/5928754/58152619-93a1a780-7c9f-11e9-834a-e4b27f864f91.png">
