### ISSUE TITLE
C/C++ highlighting incorrect

### ISSUE THREAD

**Issue by Waqar144** [crusoexia/vim-monokai#29]
Expected
----

Preprocessor Should be highlighted as '_pink_'
`struct` should be highlighted as 'aqua'
'escape sequence' should be highlighted as 'purple'

Actual
----

Preprocessor being highlighted as '_green_'
`struct` being highlighted as 'pink'
'escape sequence' being highlighted as 'pink'

**Comment by crusoexia** [comment]
@Waqar144 Could you please provide a screenshot for comparison for before vs after? I'm not a c++ dev but still want to have a direct feeling about the change.

**Comment by Waqar144** [comment]
Alright! Sure.

**Comment by Waqar144** [comment]
Before
----

![vim_bef](https://user-images.githubusercontent.com/7696024/74625357-d4b2e380-516d-11ea-81da-1d3cacaafb9d.png)

After:
-----

![vim_after](https://user-images.githubusercontent.com/7696024/74625383-e5fbf000-516d-11ea-8be6-9673ec6e7d67.png)

And the same in Sublime Text:
---

![sublime](https://user-images.githubusercontent.com/7696024/74625531-70445400-516e-11ea-953c-d09adb53a3d1.png)

**Comment by crusoexia** [comment]
Looks pretty well.
