### ISSUE TITLE
题外话：airline tab栏出现/x/h/D/是干嘛的啊？

### ISSUE THREAD

**Issue by 839891627** [crusoexia/vim-monokai#3]
看到你的tab名字那里  /x/h/D这个，这个是干嘛的啊？
我是配置了这个，就不显示 /x/h/D这些了
>let g:airline#extensions#tabline#fnamemod = ':t'    " 不显示x/h/d

**Comment by crusoexia** [comment]
你是说像 "w/s/w/index.html" 中的 "w/s/w" 是吧？
这是文件相对路径中路径部分的首字母缩写。
