### ISSUE TITLE
Tweak colour values

### ISSUE THREAD

**Issue by Macavitycode** [crusoexia/vim-monokai#33]
First off, this is a really nice colour scheme, and I like it a lot. I am looking to make a few minor tweaks though like making some colors brighter by a shade or two. How do I go about doing this? I have copied monokai.vim into ~/.vim/colors and am able to edit the colors. However, I have no understanding of how to change the colors. Please help me change the shade of some of the colors here.

**Comment by crusoexia** [comment]
You need to have some basic understanding of vim's highlight, below are some references:

1. Type `:help highlight` in the vim to see the built-in manual.
2. Refer to chapter 45-47 of [learnvimscriptthehardway](https://learnvimscriptthehardway.stevelosh.com/). This online book is also a great resource to learn the vimscript.

**Comment by Macavitycode** [comment]
Will do that thanks :)

**Comment by Macavitycode** [comment]
I got it. Thanks for the references :).
