### ISSUE TITLE
JS highlighting is off

### ISSUE THREAD

**Issue by Macavitycode** [crusoexia/vim-monokai#34]
While editing a react JS file, the highlight seems to be affecting the <> if the tag rather than the tag values as seen in the screenshot. I installed plugins like vim-javascript, vim-javascript-lib and yats.vim (as mentioned in the readme), but this seems to have no effect on the tags used.

Before plugins:
![Screenshot from 2020-06-14 16-23-09](https://user-images.githubusercontent.com/50370816/84591380-854e9c80-ae5b-11ea-9003-b30cb6a30df1.png)

After plugins:
![Screenshot from 2020-06-14 16-16-01](https://user-images.githubusercontent.com/50370816/84591302-e4f87800-ae5a-11ea-8a3b-f41e04aa55eb.png)

**Comment by crusoexia** [comment]
You need [vim-jsx](https://github.com/mxw/vim-jsx)

**Comment by crusoexia** [comment]
Oh, just noticed it is *deprecated*. Then use [vim-jsx-pretty](https://github.com/MaxMEllon/vim-jsx-pretty) instead.
