### ISSUE TITLE
Unreadable text on inactive window statusline

### ISSUE THREAD

**Issue by mkalinski** [crusoexia/vim-monokai#38]
The foreground and background combination for non-active windows' statuslines is almost completely unreadable.

![nvim-monokai](https://user-images.githubusercontent.com/959502/94997582-6a3f9e00-05ac-11eb-8ed6-cbbf0b6f0375.png)

The upper window is active and the lower one is inactive.

The screenshot was taken in Neovim v0.4.4 in terminal Kitty v0.18.3, with `set termguicolors`.

**Comment by crusoexia** [comment]
Is it the native statusline?

**Comment by crusoexia** [comment]
After the change:

<img width="718" alt="Screen Shot 2020-10-10 at 1 48 28 PM" src="https://user-images.githubusercontent.com/5928754/95646878-58f01780-0aff-11eb-9a54-559f4a7f2697.png">

**Comment by crusoexia** [comment]
@mkalinski see if it works for you.

**Comment by mkalinski** [comment]
Yes, it was the native statusline.

After update it looks for me the same as in your screenshot, so the issue is solved, thanks.
