### ISSUE TITLE
The markdown code snippet symbol doesn't render

### ISSUE THREAD

**Issue by crusoexia** [crusoexia/vim-monokai#44]
### Env
* Windows11 wsl ubuntu
* neovim v0.6.1
* windows terminal

The markdown code snippet symbol doesn't render at line `24`.
![image](https://user-images.githubusercontent.com/5928754/175764734-77cf1fc0-fffe-48ab-aa77-46f6ca77eed9.png)

When move the cursor line to line `24`, we can see the symbol is rendered.
![image](https://user-images.githubusercontent.com/5928754/175764706-66ce4ea4-03de-431b-b5ec-a69a030df0f6.png)

expected:
The code snippet symbol should be rendered.

**Comment by crusoexia** [comment]
Also doesn't work in `termux`, neovim v0.7.0

**Comment by crusoexia** [comment]
Update: it only disappear when the symbol is `javascript` . It renders good when there is no language symbol or just replace as  `js`.

![image](https://user-images.githubusercontent.com/5928754/175766684-da287b80-b7f0-4d94-8e03-760093aca3ed.png)

**Comment by jrwrigh** [comment]
Probably a `conceallevel` thing. Like one of your plugins (probably a markdown one) is set to conceal then. If you run `:set conceallevel=0`, that should probably make it visible.

**Comment by crusoexia** [comment]
> Probably a `conceallevel` thing. Like one of your plugins (probably a markdown one) is set to conceal then. If you run `:set conceallevel=0`, that should probably make it visible.

It works like a charm! 

One interesting thing is it still work on my mac iterm2 without `:set conceallevel=0`. I will dig deeper of this `conceallevel` thing. Anyway this issue is resolved. Thank you @jrwrigh .
