### ISSUE TITLE
Add syntax enable to the Readme

### ISSUE THREAD

**Issue by shouston3** [crusoexia/vim-monokai#5]
Love the color scheme and have managed to get it working, but I was not able to set it up just by following the readme.

I had to add:

    syntax enable
    colorscheme monokai

instead of just:

    colorscheme monokai

to my `.vimrc`

I noticed that there was a closed issue where someone was perhaps having a similar problem.

Maybe include this at the bottom of the readme

**Comment by crusoexia** [comment]
Thanks to point it out, already added.
