### ISSUE TITLE
Array methods does not get highlighted

### ISSUE THREAD

**Issue by cjnucette** [crusoexia/vim-monokai#6]
Hi, array methods doesn't get highlighted:

![screenshot from 2016-05-03 17-12-30](https://cloud.githubusercontent.com/assets/2278326/14998539/39b6e29a-114e-11e6-9d1d-7cc780777586.png)

I'm using pangloss/javascript and crusoexia/vim-javascript-lib.

**Comment by crusoexia** [comment]
consider to add to pangloss/vim-javascript or crusoexia/vim-javascript-lib

**Comment by cjnucette** [comment]
Yes, I'm using those plugins. I wrote it last in the previous comment.

**Comment by crusoexia** [comment]
@cjnucette please update the [vim-javascript-lib](https://github.com/crusoexia/vim-javascript-lib) and enjoy.
