### ISSUE TITLE
ES6 Functions not being highlighted

### ISSUE THREAD

**Issue by onlymejosh** [crusoexia/vim-monokai#8]
I'm having issue getting highlighting working for ES5 functions everything is appearing white
![ss](http://cl.ly/3e1g40182z2E/src)

I have the following plugins installed:
```
Plugin 'b4b4r07/vim-hcl'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'cespare/vim-toml'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'depuracao/vim-rdoc'
Plugin 'elixir-lang/vim-elixir'
Plugin 'groenewege/vim-less'
Plugin 'jceb/vim-orgmode'
Plugin 'jnwhiteh/vim-golang'
Plugin 'joukevandermaas/vim-ember-hbs'
Plugin 'leafgarland/typescript-vim'
Plugin 'mileszs/ack.vim'
Plugin 'nanki/treetop.vim'
Plugin 'othree/html5.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'rizzatti/dash.vim'
Plugin 'scrooloose/syntastic'
Plugin 't9md/vim-ruby-xmpfilter'
Plugin 'toyamarinyon/vim-swift'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-cucumber'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-projectionist'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-speeddating'
Plugin 'vim-scripts/Align'
Plugin 'vim-scripts/JSON.vim'
Plugin 'vim-scripts/ag.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
```

All of which are up to date. Is there anything glaringly obvious I've missed out?

**Comment by crusoexia** [comment]
I will check it later, to see whether vim-javascript covered this case. But it works for ES6 function which is defined in a `class`.

**Comment by crusoexia** [comment]
No luck, [vim-javascript](https://github.com/pangloss/vim-javascript) does not consider ·Ember.Component.extend({})· is a class definition, so does the ES2015 specification. Though vim-monokai is mainly focus on javascript, but it is leverage [vim-javascript](https://github.com/pangloss/vim-javascript) for the js syntax match, You'd better create an issue under [vim-javascript](https://github.com/pangloss/vim-javascript) to see whether they want to support it.

**Comment by onlymejosh** [comment]
Thanks for your help @crusoexia! This isn't a class issue though you can define functions like that in objects too. 

I'll create an issue on vim-javascript
